CREATE OR REPLACE  PROCEDURE cargar_valores_bancos AS
  CURSOR CONTROL_BANCOS IS
    SELECT A.FECHA_LIQ AS FECHA,
           DECODE(A.TP_ID, 19, 2, 3) AS BANCOS,
           SUM(A.MONTO) VALOR
      FROM MERCURY.TBL_VALOR_CONSIGNAR_MRC@CRO_MERCURY A
     WHERE A.TP_ID IN (19, 20)
     GROUP BY A.FECHA_LIQ, A.TP_ID
    MINUS
    SELECT *
      FROM CRO.TBL_VALOR_CONSIGNAR_CPT TVCC
     WHERE TVCC.ID_PYT IN (2, 3)
     ORDER BY 1 DESC;

  LIST_CONTROL VARCHAR2(2000);

  VALORES CRO.TBL_VALOR_CONSIGNAR_CPT%ROWTYPE;

BEGIN
  FOR I IN CONTROL_BANCOS LOOP
    IF CONTROL_BANCOS %FOUND THEN
      VALORES.FECHA := I.FECHA;
    
      VALORES.ID_PYT := I.BANCOS;
    
      VALORES.VALOR := I.VALOR;
      INSERT INTO CRO.TBL_VALOR_CONSIGNAR_CPT VALUES VALORES;
    ELSE
      DBMS_OUTPUT.PUT_LINE('LOS REGISTROS ESTAN AL DIA');
    END IF;
  END LOOP;

  COMMIT;
END;


SELECT * FROM user_objects uo
	WHERE uo.OBJECT_TYPE = UPPER('procedure')
	AND LOWER(uo.OBJECT_NAME) = 'cargar_valores_bancos' 

BEGIN
	cro.cargar_valores_bancos();
END;

