CREATE OR REPLACE PROCEDURE cargar_valores_a_consignar AS
	
	CURSOR VALOR_CONSIGNAR IS 
		SELECT
	A.FECHA_LIQ,
	1 AS ID_PYT,
	SUM(A.MONTO) AS VALOR
		FROM
			MERCURY.TBL_VALOR_CONSIGNAR_MRC@CRO_MERCURY A
		WHERE
			A.TP_ID IN (16, 44, 745)
			AND EXTRACT (YEAR
		FROM
			A.FECHA_LIQ) = EXTRACT(YEAR FROM SYSDATE)
		GROUP BY
			A.FECHA_LIQ
		MINUS 
		SELECT
			*
		FROM
			CRO.TBL_VALOR_CONSIGNAR_CPT TVCC
		WHERE
			TVCC.ID_PYT = 1
		ORDER BY
			1;

	VALORES CRO.TBL_VALOR_CONSIGNAR_CPT%ROWTYPE;

BEGIN
	FOR I IN VALOR_CONSIGNAR LOOP
		IF VALOR_CONSIGNAR%FOUND THEN
			VALORES.FECHA := I.FECHA_LIQ;
			VALORES.ID_PYT := I.ID_PYT;
			VALORES.VALOR := I.VALOR;
		
			INSERT INTO CRO.TBL_VALOR_CONSIGNAR_CPT VALUES VALORES;
			
		END IF;
		
	END LOOP;
	COMMIT; 
END;

SELECT * FROM user_objects
	WHERE object_name = UPPER('cargar_valores_a_consignar')
