SELECT C."FECHA USO", NVL(C.USOS, 0) AS "PRODUCT USOS", NVL(C.VISA, 0) AS "USOS VISA" FROM (SELECT *
  FROM (SELECT TO_CHAR(A.CU_DATETIME, 'DD-MM-YYYY') AS "FECHA USO",
               COUNT(CU_DATETIME) AS "CANTIDAD DE USOS",
               'USOS' TIPO
          FROM MERCURY.TBL_LIQUIDACIONRYT_USOS A
         WHERE  
           TRUNC(A.CLEARING_DATE) >= TO_DATE('01-10-2023', 'DD-MM-YYYY')
           AND TRUNC(A.CLEARING_DATE) <= TO_DATE('31-10-2023', 'DD-MM-YYYY')
           AND A.CU_ITG_CTR IS NULL
           AND A.TP_ID  NOT IN (44, 999)
           AND A.CU_FAREVALUE > 0
           AND A.LD_ID NOT IN (215)
         GROUP BY TO_CHAR(A.CU_DATETIME, 'DD-MM-YYYY')
        HAVING COUNT(CU_DATETIME) > 0
        UNION
        SELECT TO_CHAR(A.CU_DATETIME, 'DD-MM-YYYY') AS "FECHA USOS VISA",
              NVL(COUNT(CU_DATETIME), 0) AS "CANTIDAD DE USOS", 
               'VISA' TIPO
          FROM MERCURY.TBL_LIQUIDACIONRYT_USOS A
         WHERE 
           TRUNC(A.CLEARING_DATE) >= TO_DATE('01-10-2023', 'DD-MM-YYYY')
           AND TRUNC(A.CLEARING_DATE) <= TO_DATE('31-10-2023', 'DD-MM-YYYY')
            AND A.CU_ITG_CTR IS NULL
           AND A.TP_ID = 999 
           AND A.CU_FAREVALUE > 0
           AND A.TP_ID <> 44
           AND A.LD_ID NOT IN (215)
         GROUP BY TO_CHAR(A.CU_DATETIME, 'DD-MM-YYYY')
        HAVING COUNT(CU_DATETIME) > 0)B
PIVOT(SUM("CANTIDAD DE USOS") FOR TIPO IN ('USOS' USOS, 'VISA' VISA)))C