/*SELECT
	A.CU_DAT_INC_PUENTE,
	TO_CHAR(A.CU_DATETIME, 'dd Month, yyyy'),
	A.LD_ID,
	A.VEH_ID,
	COUNT(4) CANTIDAD,
	CU_FAREVALUE,
	TRUNC(CLEARING_REG),
	TO_CHAR((A.CU_DAT_INC_PUENTE) - 1, 'dd-mm-yyyy')
FROM
	TBL_LIQUIDACIONRYT_USOS A */
UPDATE MERCURY.TBL_LIQUIDACIONRYT_USOS A
SET
  A.CU_DATETIME = TO_DATE(
    TO_CHAR((A.CU_DAT_INC_PUENTE) - 1, 'dd-mm-yyyy ')
    || ' '
    || TO_CHAR(A.CU_DATETIME, 'hh24:mi:ss'),
    'dd-mm-yyyy hh24:mi:ss'
  )
/*SELECT ROWID, a.*
FROM tbl_liquidacionryt_usos a*/
WHERE
	TO_CHAR(A.CLEARING_REG, 'dd-mm-yyyy') = TO_CHAR(SYSDATE, 'dd-mm-yyyy')
	-- Fecha Registro
	-- AND TO_CHAR(A.CU_DATETIME, 'dd-mm-yyyy') IN ('05-06-2022')
	AND TO_CHAR(A.CU_DATETIME, 'yyyy') NOT IN (2023, 2024)
	-- AND A.VEH_ID IN (504)
	-- AND a.ld_id = 60
	AND (a.cu_farevalue <> 2700 OR a.CU_FAREVALUE = 2700)
	AND A.CU_ITG_CTR IS NULL
	-- BANCOS
	AND A.APP_ID NOT IN (902, 920)
	
	AND (A.TP_ID NOT IN (999)
		OR (A.TP_ID = 999
			AND A.CU_FAREVALUE > 0))
GROUP BY
	A.CU_DAT_INC_PUENTE,
	A.VEH_ID,
	CU_FAREVALUE,
	A.LD_ID,
	TRUNC(CLEARING_REG),
	TO_CHAR(A.CU_DATETIME, 'dd Month, yyyy');

405

/

SELECT
  A.APP_DESCSHORT,
  A.APP_ID
FROM
  TBL_LIQUIDACIONRYT_USOS A
GROUP BY
  A.APP_DESCSHORT,
  A.APP_ID;

SELECT
  *
FROM
  MERCURY.TBL_VALIDADORES_MRC VL
WHERE
  VL.VEH_ID = 5901

/

SELECT
  A.FECHA_TRX,
  SUM(A.MONTO) VALOR
FROM
  MERCURY.TBL_VALOR_CONSIGNAR_MRC A
WHERE
  A.FECHA_LIQ = TO_DATE('02-06-2023', 'dd-mm-yyyy')
  AND A.TP_ID IN (16, 44, 745) --(16, 44, 745)
GROUP BY
  A.FECHA_TRX
ORDER BY
  1 ASC;

/

SELECT
  TRUNC(CU.CU_DATETIME) FECH_USO,
  (UDF.VEH_ID)
  || ' - '
  || LD.LD_DESC         AS USO_VALIDADOR,
  COUNT(1)              CANTIDAD_REG,
  CU.CU_DAT_INC_PUENTE  FECH_COMUNICACI�N
FROM
  MERCURY.CARDUSAGE        CU,
  MERCURY.LINEDETAILS      LD,
  MERCURY.USAGEDATATRIPMT  UDTM,
  MERCURY.USAGEDATASERVICE UDS,
  MERCURY.USAGEDATAFILE    UDF,
  MERCURY.APPLICATIONS     APP
WHERE
  CU.UDTM_ID = UDTM.UDTM_ID
  AND UDTM.UDS_ID = UDS.UDS_ID
  AND UDS.UDF_ID = UDF.UDF_ID
  AND TRUNC(CU.CU_DAT_INC_PUENTE) >= TO_DATE(SYSDATE - 5) -- TO_DATE('09-06-2023', 'dd-mm-yyyy')
  AND TRUNC(CU.CU_DAT_INC_PUENTE) <= TO_DATE(SYSDATE) -- TO_DATE('13-06-2023', 'dd-mm-yyyy')
  AND CU.CUT_ID = 1 -- Tipos de uso -> 1: Passenger use, 5: On-board sale
  AND NVL(CU.CU_PARTFARESEQNBR, 0) <> 2 -- Solo cuenta una vez las transacciones que afectan las dos cuentas de la tarjeta.
  AND APP.APP_ID = CU.APP_ID
  AND LD.LD_ID = CU.LD_ID
  AND UDF.TP_ID <> 25
  AND CU.CU_ITG_CTR IS NULL
  AND ((CU.CU_FAREVALUE > 0)
  OR CU.APP_ID IN (920, 902)) -- Solo usos pagos 'BANBOGOTA - BANCOLOMBIA'
  AND (TO_CHAR(CU.CU_DATETIME, 'yyyy') <> 2023
  OR TRUNC(CU.CU_DATETIME) = TO_DATE(SYSDATE - 120)
  OR TRUNC(CU.CU_DATETIME) > TO_DATE(SYSDATE))
GROUP BY
  TRUNC(CU.CU_DATETIME), LD.LD_DESC, UD�F.VEH_ID, CU.CU_DAT_INC_PUENTE;

/